### ISSUE TITLE
amazon dash buttons post repeatedly

### ISSUE THREAD

**Issue by abzman** [i3detroit/homeassistant-config#10]
each button should have an individual cooldown so it doesn't post more than once per minute, but collectively the buttons should be able to post many times a minute

**Comment by mkfink** [comment]
To convert dash.io options.json to dasher config.json for use in home assistant:
find<pre>
\s\s\{\s\s\s\s\s"name": "(.+)",[.\n\s]+"address":\s"([\d:a-f]+)",\n[\n\s"a-z:,_\{\\]+script\.([a-z_\d]+)\\"}"\n\s\s\}
</pre>replace<pre>
  {
    "name": "\1",
    "address": "\2",
    "timeout": "60000",
    "protocol": "udp",
    "method": "POST",
    "url": "http://10.13.0.22:8123/api/services/script/turn_on",
    "json": true,
    "body": {"entity_id": "script.\3"}
  }
</pre>

**Comment by mkfink** [comment]
https://github.com/i3detroit/homeassistant-config/commit/3c25a95cbef06a42cf8d124fc2f4224c8193bcac

Done
