### ISSUE TITLE
get homeassistant to yell at slack when the accumulated water through the filter is near the limit

### ISSUE THREAD

**Issue by abzman** [i3detroit/homeassistant-config#15]

**Comment by mkfink** [comment]
Need to add https://www.home-assistant.io/components/sensor.influxdb/ to get summed value of flow counts. Could also use this to show accumulated laser time in home assistant, and there are probably other interesting stats.

**Comment by mkfink** [comment]
https://github.com/i3detroit/homeassistant-config/commit/8c34f535e5ff094819632a51545e2905abb3adbb

Done
